version: '3.8'

services:
  frontend:
    image: vou-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run dev